version: "3.9"

services:
  mongo:
    image: "mongo"
    restart: always

  mongo-express:
    image: "mongo-express"
    depends_on:
      - mongo
    ports:
      - 8081:8081

  backend:
    build: backend
    depends_on:
      - mongo
    volumes:
      - ./backend:/backend
    ports:
      - 5000:5000

  frontend:
    build: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
